algoritmo " retangulo "
// Função :
// Autor : gabriela akiko
// Data : 18/02/2020
// Seção de Declarações 
var
 base, altura, result1, result2:real
inicio
// Seção de Comandos 
//entrada
escreval("digite a base o do retângulo em cm")
leia(base)
escreval("digite a altura do retangulo em cm")
leia(altura)
//processamento
result1<-base*altura
result2<-(base*2)+ (altura*2)
//saída
escreval("a área do retangulo è:",result1, "cm")
escreval("o perímetro do retangulo é :",result2, "cm")
fimalgoritmo
