algoritmo "QUADRADO"
// Função :  informar a area e o perimetro do quadrado
// Autor :   gabriela akiko
// Data : 18/02/2020
// Seção de Declarações 
var
 lado,resp,resp2:real
inicio
// Seção de Comandos 
//entrada
escreval("digite o lado do quadrado em centimetros")
leia(lado)
//processamento
resp<-lado^2
resp2<-lado*4
//saída
escreval("a àrea é:",resp,"cm")
escreval("o perímetro é:",resp,"cm")
fimalgoritmo
