algoritmo "ESTOQUEMEDIO"
// Função :  Calcular o valor total do estoque medio
// Autor :    Gabriela Akiko
// Data : 03/03/2020
// Seção de Declarações 
var
QTMIN, QTMAX, VALOR:real

inicio
//entrada
escreval(" qual a quantidade mínima de peças?")
        leia(QTMIN)
        ESCREVAL("Qual aquantidade maxia de peças")
        leia(QTMAX)
//processament
         VALOR<-(QTMIN+QTMAX)/2
//saída
          Escreval(" o estoque médio é :",VALOR )
        
fimalgoritmo
